[build]
  command = "npx nuxi build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max_old_space_size=4096"
  PNPM_FLAGS = "--shamefully-hoist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 