[build]
  command = "NODE_OPTIONS=--max_old_space_size=4096 npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_BUILD_DEBUG = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 