[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_BUILD_DEBUG = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 